"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cw3lt*dsvs*osvn8&6$3j3f#(&ty#gwwim2%^bn6^)39vizb3c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Apps base de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto
    'users',
    'finances',

    # Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',

    # Librerías para documentación OpenAPI
    'drf_spectacular',
    'drf_spectacular_sidecar',  # Archivos estáticos (Swagger UI, Redoc)

    # black list para JWT
    'rest_framework_simplejwt.token_blacklist',

    # cors headers
    'corsheaders',

]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Puerto de React (vite)
]

CORS_ALLOW_CREDENTIALS = True


# ===========================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK
# ===========================================

REST_FRAMEWORK = {
    # Filtros: django-filters
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # Autenticación: JWT para usuarios
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Permisos por defecto (solo usuarios autenticados)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Esquema de documentación: DRF Spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Paginacion por defecto
    
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 10,

    # Manejador de excepciones personalizado
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Seguridad básica
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}



# ===========================================
#  CONFIGURACIÓN DE DRF SPECTACULAR
# ===========================================
# Esto define los metadatos de la documentación: título, contacto, licencia, etc.

SPECTACULAR_SETTINGS = {
    'TITLE': 'MiDinero API',
    'DESCRIPTION': 'API REST para gestión de finanzas personales (ingresos, gastos, metas y más).',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # evita duplicar la vista raíz
    # Informacion de contacto y licencia
    'CONTACT': {
        'name': 'Camilo Álvarez',
        'email': 'soporte@midinero.com',
        'url': 'https://midinero.com',
    },
    # Licencia
    'LICENSE': {
        'name': 'MIT License',
        'url': 'https://opensource.org/licenses/MIT',
    },
    # Ajustes adicionales
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
}



# ===========================================
# CONFIGURACIÓN DE JWT
# ===========================================

from datetime import timedelta

SIMPLE_JWT = {
    # Duración del token de acceso (usado para autenticación en React)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),

    # Duración del token de refresco (para renovar sin volver a loguearse)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Permite rotar tokens de refresco al renovarlos (opcional pero más seguro)
    'ROTATE_REFRESH_TOKENS': True,

    # Invalida los tokens antiguos al rotar
    'BLACKLIST_AFTER_ROTATION': True,

    # Tipo de autenticación esperado en los headers HTTP
    # React deberá enviar: Authorization: Bearer <access_token>
    'AUTH_HEADER_TYPES': ('Bearer',),

    # Clave usada para firmar los tokens
    'SIGNING_KEY': SECRET_KEY,

    # Algoritmo de firma
    'ALGORITHM': 'HS256',

    # Configura el campo de usuario para autenticación
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ===========================================
# CONFIGURACIÓN DE CORREO (Email Backend)
# ===========================================

# Para pruebas locales (muestra los correos en la consola)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'FinanzasApp <no-reply@finanzas.com>'

# Si luego quieres enviarlos realmente, puedes usar Gmail u otro SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tucorreo@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu_contraseña_o_token'
# DEFAULT_FROM_EMAIL = 'FinanzasApp <tucorreo@gmail.com>'
